apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  generateName: dag-params-
spec:
  entrypoint: ml-pipeline

  arguments:
    parameters:
    - name: dataset
      value: iris.csv
    - name: learning-rate
      value: "0.01"


  templates:
  - name: ml-pipeline
    dag: 
      tasks:
      
      - name: preprocess
        template: preprocess
        arguments: 
          parameters:
          - name: dataset
            value: "{{workflow.parameters.dataset}}"
      
      - name: train
        template: train
        arguments: 
          parameters:
          - name: lr
            value: "{{workflow.parameters.learning-rate}}"
        dependencies: [preprocess]

      - name: evaluate
        template: evaluate
        dependencies: [train]

  - name: preprocess
    inputs:
      parameters:
      - name: dataset
    container:
      image: alpine:3.19
      command: [sh, -c]
      args: 
        - | 
          echo "Preprocessing dataset: {{inputs.parameters.dataset}}"
          sleep 2

  - name: train
    inputs:
      parameters:
      - name: lr
    container:
      image: alpine:3.19
      command: [sh, -c]
      args:
        - |
          echo "Training model with learning rate = {{inputs.parameters.lr}}"
          sleep 2

  - name: evaluate
    container: 
      image: alpine:3.19
      command: [sh, -c]
      args: 
        - |
          echo "Evaluating Model...."
          sleep 2
