apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  generateName: ml-artifacts-

spec: 
  entrypoint: ml-pipeline

  templates:
  - name: ml-pipeline
    dag:
      tasks:
      - name: prepare-data
        template: prepare-data

      - name: train-model
        template: train-model
        dependencies: [prepare-data]
        arguments:
          artifacts:
          - name: dataset
            from: "{{tasks.prepare-data.outputs.artifacts.dataset}}"

      - name: evaluate-model
        template: evaluate-model
        dependencies: [train-model]
        arguments:
          artifacts:
          - name: model
            from: "{{tasks.train-model.outputs.artifacts.model}}"

  - name: prepare-data
    container: 
      image: alpine:3.19
      command: [sh, -c]
      args:
        - | 
          echo "sepal_length,sepal_width,petal_length,petal_width,label" > /tmp/dataset.csv
          echo "5.1,3.5,1.4,0.2,setosa" >> /tmp/dataset.csv
          echo "5.9,3.0,5.1,1.8,virginica" >> /tmp/dataset.csv
    outputs:
      artifacts:
      - name: dataset
        path: /tmp/dataset.csv


  - name: train-model
    inputs:
      artifacts:
      - name: dataset
        path: /tmp/dataset.csv
    container:
      image: alpine:3.19
      command: [sh, -c]
      args:
          - |
            echo "Training model using dataset:"
            wc -1 /tmp/dataset.csv
            echo "MODEL_WEIGHTS=0.42" > /tmp/model.txt

    outputs:
      artifacts:
      - name: model
        path: /tmp/model.txt


  - name: evaluate-model
    inputs:
      artifacts:
      - name: model
        path: /tmp/model.txt
    container:
      image: alpine:3.19
      command: [sh, -c]
      args:
        - |
          echo "Evaluating Model:"
          cat /tmp/model.txt
          echo "accuracy=0.95"
